### ISSUE TITLE
server process's TCPConnection::HandleError() was triggerred when force killed client process(Platform:Windows)

### ISSUE THREAD

**Issue by oceancx** [kingsamchen/ezio#3]
i saw the call stack, this error frome Notifier::DoHandleEvent, and IOEventType is 2 or 3, and the socket error code is 10054 (WSAECONNRESET).

this issue troubles me a lot, cause i can't remove the connection when client is disconnected.

**Comment by kingsamchen** [comment]
This issue is confirmed, and yet, same behavior on Linux will casue no trouble.

**Comment by kingsamchen** [comment]
@oceancx This issue has presumably been fixed in this [commit](https://github.com/kingsamchen/ezio/commit/8d25596c66234322ee71ea249390559205df2a4b), I guess.

Could you try this commit out and to see if the issue was fixed?

**Comment by kingsamchen** [comment]
The issue has been fixed and the patch would be merge into branch master.
