### ISSUE TITLE
bug: once send message over 1024 bytes, the receive side will close tcpconncetion (windows)

### ISSUE THREAD

**Issue by oceancx** [kingsamchen/ezio#4]
for instance, client side send 1600 bytes. server side only can read 1024 bytes one time, then for the next _on_read event, bytes_transferred is 0, and server will close the connection.

**Comment by kingsamchen** [comment]
This issue is confirmed; and I believe it has something to do with buffer handling of `PostRead()` in Windows implementation.

Anyway, thanks for filing the issue.

**Comment by kingsamchen** [comment]
I suppose the patch should have fixed the issue.
